apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-urjl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-urjl@sha256:8793c9d6b354983995aaa2e6d887d21b2b26f0dd2d2cf4294fa4916430d393b3
        name: my-nodejs
        resources: {}
status: {}
